# Stage 1: Build the application
FROM node:24-alpine AS builder

ENV NODE_OPTIONS=--max-old-space-size=4000

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy package files and install dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Copy the rest of the application source code
COPY . .

# Build the application
#ARG NODE_ENV
ARG BASE_URL
ARG VITE_BASE_URL
ARG WAGMI_PROJECT_ID


#ENV NODE_ENV=${NODE_ENV}
ENV BASE_URL=${BASE_URL}
ENV VITE_BASE_URL=${VITE_BASE_URL}
ENV VITE_SENTRY_DSN=${VITE_SENTRY_DSN}
ENV VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
RUN pnpm build

# Expose the port the app runs on
EXPOSE 3000

# The command to run the application
CMD ["node", ".output/server/index.mjs"]
