substitutions:
  _BASE_URL: "https://url.io"
  _VITE_BASE_URL: "https://url.io"
  _WAGMI_PROJECT_ID: "xx"
  _VITE_GOOGLE_MAPS_API_KEY: "xx"

steps:
  - args:
      - build
      - -t
      - eu.gcr.io/i-condition-468114-k8/github.com/author/repo_name:$BRANCH_NAME
      - --build-arg
      - BASE_URL=${_BASE_URL}
      - --build-arg
      - VITE_BASE_URL=${_VITE_BASE_URL}
      - --build-arg
      - VITE_SENTRY_DSN=${_VITE_SENTRY_DSN}
      - --build-arg
      - VITE_GOOGLE_MAPS_API_KEY=${_VITE_GOOGLE_MAPS_API_KEY}
      - .
    name: gcr.io/cloud-builders/docker

images:
  - eu.gcr.io/i-condition-468114-k8/github.com/author/repo_name:$BRANCH_NAME

options:
  machineType: "E2_HIGHCPU_8" # 8 vCPUs, 8 GB memory
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
